version: "3.7"
services:
  vpn-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  traffic-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
